// bench_vt_throughput — throughput benchmark for the PTY → VtParser →
// TerminalGrid hot path. Drives the investigation plan documented in
// ROADMAP.md § 0.8.0 > ⚡ Performance > "Terminal throughput slowdowns"
// (user report 2026-04-20: "slow down experienced now and then").
//
// The benchmark links only terminalgrid.cpp + vtparser.cpp plus Qt6::Core
// + Qt6::Gui — no QApplication, no widget tree, no PTY. It feeds
// pre-generated byte corpora through VtParser whose ActionCallback
// forwards each action to a single TerminalGrid. Wall time is measured
// around the feed + processAction loop only (corpus generation excluded).
//
// Corpora are designed to isolate hot-path costs:
//   - `ascii_print`       — Print-only bytes, no control sequences. Exercises
//                           UTF-8 fast path + TerminalGrid::printChar.
//   - `newline_stream`    — `hello\n` lines. Adds Execute(LF) which triggers
//                           cursor carriage + lineFeed + scroll handling.
//   - `ansi_sgr`          — colored-log output. Mixes Print with CSI SGR
//                           sequences, exercising the VT parser state
//                           transitions + TerminalGrid's SGR dispatch.
//   - `utf8_cjk`          — CJK Han characters (3-byte UTF-8). Stresses
//                           the UTF-8 decode + double-width cell handling.
//
// Output format is deliberately machine-parseable — a single CSV line
// per corpus — so a future CI job can compare two runs and flag
// regressions. Example:
//
//   corpus,bytes,actions,wall_ms,MB_per_sec,actions_per_sec
//   ascii_print,10485760,10485760,123.4,85.03,84973904.37
//
// Pass criteria (current): none. The benchmark exits 0 as long as it
// completes without crashing; CI picks up the numbers from stdout. A
// later commit will add a floor-based regression gate.

#include "terminalgrid.h"
#include "vtparser.h"

#include <chrono>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

namespace {

struct BenchResult {
    std::string corpus;
    size_t bytes;
    size_t actions;
    double wallMs;
};

std::string makeAsciiPrint(size_t targetBytes) {
    static const char kLine[] =
        "The quick brown fox jumps over the lazy dog 0123456789.";
    std::string buf;
    buf.reserve(targetBytes);
    while (buf.size() < targetBytes) {
        buf.append(kLine, sizeof(kLine) - 1);
    }
    buf.resize(targetBytes);
    return buf;
}

std::string makeNewlineStream(size_t targetBytes) {
    static const char kLine[] = "hello world\n";
    const size_t n = sizeof(kLine) - 1;
    std::string buf;
    buf.reserve(targetBytes + n);
    while (buf.size() < targetBytes) {
        buf.append(kLine, n);
    }
    return buf;
}

std::string makeAnsiSgr(size_t targetBytes) {
    // Mix of foreground color change + bold + reset. Shape mirrors
    // `ls --color=always` / `grep --color=always` output.
    static const char kLine[] =
        "\x1b[1;32m[INFO]\x1b[0m connection established to \x1b[36mhost.example.com\x1b[0m port \x1b[33m443\x1b[0m\n"
        "\x1b[1;31m[ERR ]\x1b[0m timeout after \x1b[33m30s\x1b[0m retrying...\n";
    const size_t n = sizeof(kLine) - 1;
    std::string buf;
    buf.reserve(targetBytes + n);
    while (buf.size() < targetBytes) {
        buf.append(kLine, n);
    }
    return buf;
}

std::string makeUtf8Cjk(size_t targetBytes) {
    // "今日は世界" repeated. Each Han char is 3 UTF-8 bytes, double-width.
    static const char kLine[] =
        "\xe4\xbb\x8a\xe6\x97\xa5\xe3\x81\xaf\xe4\xb8\x96\xe7\x95\x8c\n";
    const size_t n = sizeof(kLine) - 1;
    std::string buf;
    buf.reserve(targetBytes + n);
    while (buf.size() < targetBytes) {
        buf.append(kLine, n);
    }
    return buf;
}

BenchResult runOne(const char *name, const std::string &payload, int rows, int cols) {
    TerminalGrid grid(rows, cols);
    size_t actionCount = 0;
    VtParser parser([&grid, &actionCount](const VtAction &action) {
        grid.processAction(action);
        ++actionCount;
    });

    auto t0 = std::chrono::steady_clock::now();
    parser.feed(payload.data(), static_cast<int>(payload.size()));
    auto t1 = std::chrono::steady_clock::now();

    double wallMs = std::chrono::duration<double, std::milli>(t1 - t0).count();
    return {name, payload.size(), actionCount, wallMs};
}

void printCsvLine(const BenchResult &r) {
    const double mbPerSec = (r.wallMs > 0.0)
        ? (static_cast<double>(r.bytes) / 1'048'576.0) / (r.wallMs / 1000.0)
        : 0.0;
    const double actionsPerSec = (r.wallMs > 0.0)
        ? static_cast<double>(r.actions) / (r.wallMs / 1000.0)
        : 0.0;
    std::printf("%s,%zu,%zu,%.2f,%.2f,%.2f\n",
                r.corpus.c_str(), r.bytes, r.actions, r.wallMs,
                mbPerSec, actionsPerSec);
}

}  // namespace

int main(int argc, char *argv[]) {
    // Corpus size override: `ANTS_PERF_MB=64` runs 64 MB per corpus.
    // Default 4 MB — keeps the full run under ~500 ms on a 2020-era
    // laptop so the harness can sit in the default `ctest -L perf`
    // lane without stretching runner budgets.
    size_t mb = 4;
    if (const char *env = std::getenv("ANTS_PERF_MB")) {
        char *end = nullptr;
        long v = std::strtol(env, &end, 10);
        if (end != env && v > 0 && v < 1024) mb = static_cast<size_t>(v);
    }
    // CLI override: `bench_vt_throughput --mb 64` wins over env.
    for (int i = 1; i < argc; ++i) {
        if (std::strcmp(argv[i], "--mb") == 0 && i + 1 < argc) {
            char *end = nullptr;
            long v = std::strtol(argv[i + 1], &end, 10);
            if (end != argv[i + 1] && v > 0 && v < 1024)
                mb = static_cast<size_t>(v);
        }
    }
    const size_t targetBytes = mb * 1'048'576;
    constexpr int kRows = 40;
    constexpr int kCols = 160;

    std::printf("corpus,bytes,actions,wall_ms,MB_per_sec,actions_per_sec\n");

    std::vector<std::pair<std::string, std::string>> corpora;
    corpora.emplace_back("ascii_print",    makeAsciiPrint(targetBytes));
    corpora.emplace_back("newline_stream", makeNewlineStream(targetBytes));
    corpora.emplace_back("ansi_sgr",       makeAnsiSgr(targetBytes));
    corpora.emplace_back("utf8_cjk",       makeUtf8Cjk(targetBytes));

    for (const auto &[name, payload] : corpora) {
        BenchResult r = runOne(name.c_str(), payload, kRows, kCols);
        printCsvLine(r);
    }
    return 0;
}
